// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfY9O0mVjXcHH-YJEMHCKTlGuf8EikZ0',
    appId: '1:545631128057:web:10ea761d10387dc86a9528',
    messagingSenderId: '545631128057',
    projectId: 'moral-9f5c7',
    authDomain: 'moral-9f5c7.firebaseapp.com',
    databaseURL: 'https://moral-9f5c7-default-rtdb.firebaseio.com',
    storageBucket: 'moral-9f5c7.appspot.com',
    measurementId: 'G-4KXZB7QL5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlKy1rEVw6n9SJs7jE5EAr7x87z3U-K8',
    appId: '1:545631128057:android:c54aa1e97c3921026a9528',
    messagingSenderId: '545631128057',
    projectId: 'moral-9f5c7',
    databaseURL: 'https://moral-9f5c7-default-rtdb.firebaseio.com',
    storageBucket: 'moral-9f5c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7SIkhCzFxsEBbncqn67LD7xVs3Fr-Hw',
    appId: '1:545631128057:ios:276a9789c6685e136a9528',
    messagingSenderId: '545631128057',
    projectId: 'moral-9f5c7',
    databaseURL: 'https://moral-9f5c7-default-rtdb.firebaseio.com',
    storageBucket: 'moral-9f5c7.appspot.com',
    androidClientId: '545631128057-5ev0okdctrvb60sakdhun91ggh18evli.apps.googleusercontent.com',
    iosBundleId: 'com.moral1.fourmoral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7SIkhCzFxsEBbncqn67LD7xVs3Fr-Hw',
    appId: '1:545631128057:ios:5730d60062873b7b6a9528',
    messagingSenderId: '545631128057',
    projectId: 'moral-9f5c7',
    databaseURL: 'https://moral-9f5c7-default-rtdb.firebaseio.com',
    storageBucket: 'moral-9f5c7.appspot.com',
    androidClientId:
        '545631128057-51v5jro5kj0lr51c7ucbg6ivqlm980dp.apps.googleusercontent.com',
    iosBundleId: 'com.bts.fourmoral',
  );
}